# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-d_eI9pDGMMm25jEerQW2x3tsRohioBZ
"""

n = 16
for i in range(1,n):
    print(i)

n = 17
for i in range(n,0,-1):
 print(i)

for i in range(97,123):
 print(chr(i))

for i in range(2,101):
 if i%2==0:
    print("even no.",i)

n = 100
sum = 0
for i in range(1,n+1):
   if i%2!=0:
    sum+=i
print("odd number:",sum)

#calculate the sum of digits of number
n = int(input("enter the number"))
sum = 0

num = int(input("Enter a number: "))
count = 0
for digit in str(num):
    count = count+1
print("Total number of digits:", count)

n = int(input("enter the number:"))
sum = 0
for digit in str(n):
    sum = sum + int(digit)

print("total sum of these number",sum)

i = 20
while i < 40:
    if i % 3 == 0:
        print(i)
    i = i + 1

#q8
number = input("Enter a number: ")

first_digit = None
last_digit = None

for i in range(len(number)):
        if first_digit is None:
            first_digit = number[i]
        last_digit = number[i]

print("First digit:", first_digit)
print("Last digit:", last_digit)

number = input("enter the number")
first_digit = None
last_digit = None
for i in range(len(number)):
    if first_digit is None:
        first_digit = number[i]
    last_digit = number[i]

print("first digit",first_digit)
print("last digit",last_digit)

number = input("enter the number")
first_digit = None
last_digit = None
for i in range(len(number)):
    if first_digit is None:
        first_digit = number[i]
    last_digit = number[i]
sum_digit = int(first_digit) + int(last_digit)
print("sum of first and last digit",sum_digit)

num = 1234
reverse = str(num)[: : -1]
print("reverse",reverse)

num = 3
base = 3
print("power of these number",num**base)

number = 12
print("factors of these number")
for i in range(1,1+number):
    if number % i ==0:
        print(i)

num = int(input("enter the number"))
last_digit = 0
for digit in str(num):
    last_digit = last_digit+int(digit)
print(digit)

n = int(input("enter the number"))
factorial = 1
for i in range(n,0,-1):
    factorial = factorial*i
print("factorial of these number",factorial)

n = int(input("enter the number"))
a = 0
for i in range(2,n):
    if(n%i==0):
        a = 1
        break
if(a==0):
    print("prime number")
else:
    print("not a prime number")

n = int(input("enter the number"))
for m in range(1,n+1):
    count = 0
    for i in range(1,m+1):
        if(m%i==0):
            count = count+1
    if(count==2):
        print(m,end=" ")

n = int(input("enter the number"))
for i in range(1,n+1):
    if (n%i==0):
        print(i)

#armstrong or not
n = int(input("enter the number"))
count = 0
total = 0
temp = n
while(temp>0):
    count+=1
    temp = temp//10
temp = n
while(temp>0):
    rem = temp%10
    total = total+rem**count
    temp = temp//10
if(total==n):
    print("armstrong number")
else:
    print("not a armstrong number")

n = int(input("enter the number"))
temp = n
total = 0
while(temp>0):
    rem = temp%10
    factorial = 1
    for i in range(1,rem+1):
        factorial = factorial*i
    total = total+factorial
    temp = temp//10
if(total==n):
    print("strong number")
else:
    print("not a strong number")

n = int(input("Enter the number: "))
sum = 0
for i in range(1, n):
    if n % i == 0:
        sum += i
if sum == n:
    print("Perfect number")
else:
    print("Not a perfect number")

n = int(input("Enter the number: "))
a = 0
b = 1
for i in range(2,n+1):
    next = a+b
    a = b
    b = next
    print(b,end=" ")