# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1coBeUo6sH_HtfRUc6DkmOSc9yishnY-T
"""
#q1
n = int(input("enter the number:"))
if n%2==0:
    print("even number",n)
else:
    print("odd number",n)
#q2
#largest amog three numbers
a= int(input("enter the number:"))
b= int(input("enter the number:"))
c= int(input("enter the number:"))
if a>b and a>c:
    print("a is largest",a)
elif b>a and b>c:
    print("b is largest",b)
else:
    print("c is largest",c)
#q3
marks = int(input("enter the marks:"))
if marks>=90:
    print("grade A")
elif marks>=80:
    print("grade B")
elif marks>=70:
    print("grade C")
elif marks>=60:
    print("grade D")
else:
     print("failed")
#q4
hum = input("Enter the alphabet: ")

if  hum in "aeiou":
    print("Vowel")
else:
    print("Consonant")
#q5
a = int(input("enter the number:"))
b = int(input("enter the number:"))
print("sum",a+b)
#q6
a = int(input("enter the number:"))
b = int(input("enter the number:"))
print("sub",a-b)
#q7
a = int(input("enter the number"))
b = int(input("enter the number"))
print("multiplication",a*b)
#q8
a = int(input("enter the number"))
b = int(input("enter the number"))
print("divide",a/b)
#q9
username = input("Enter the username: ")
password = input("Enter the password: ")

if username == "admin" and password == "password123":
    print("Login successful")
else:
    print("inavid")
#10
a = int(input("enter the number:"))
b = int(input("enter the number:"))
c = int(input("enter the number:"))
if a+b>c and b+c>a and c+a>b:
    print("valid triangle")
#q11
weight = float(input("Enter your weight in kilograms: "))
height = float(input("Enter your height in meters: "))

bmi = weight / (height ** 2)

print("\nYour BMI is:", bmi)

if bmi < 18.5:
    print(" Underweight")
elif 18.5 <= bmi < 24.9:
    print(" Normal weight")
elif 25 <= bmi < 29.9:
    print(" Overweight")
else:
    print("Obesity")
#q12
num = float(input("enter the number "))
if num > 1000:
    discount = num*0.10
elif num >= 500:
    discount = num*0.5
    print("discount",discount)
else:
    discount = 0
final_price = num - discount
print("final price after the discount",final_price)
#q13
age = int(input("enter the age"))
if age >= 0 and age <= 1:
    print("infant")
elif age >=2 and age <= 3:
    print("toddler")
elif age >=5 and age<=12:
    print("child")
elif age >=13 and age<= 19:
    print("teenager")
elif age>= 20 and age <= 59:
    print("adult")
elif age <= 60:
    print("senior")
else:
    print("invaild age")
#q14
day = int(input("enter the number"))
if day ==1:
    print("sunday")
elif day ==2:
    print("monday")
elif day ==3:
    print("tuesday")
elif day ==4:
    print("wednesday")
elif day ==5:
    print("thursday")
elif day ==6:
    print("friday")
elif day ==7:
    print("saturday")
else:
    print("inavild number of day")

