# -*- coding: utf-8 -*-
"""Untitled43.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fBhTsRH2JjEF-Tum4v3ielsK2rO2enPD
"""

questionBank=[ {"Question":"What is the national animal of india?",
              "option":["A. Peacock",  "B. Lion", "C. Tiger", "D. Dog"],
              "Ans":"C",
              },
              {"Question":"Who is the father of nation?",
              "option":["A. Rabindra Nath Tagore",  "B. Mahatma Gandhi",
                        "C. Sharukh Khan", "D. Salman Khan"],
              "Ans":"B",
              }
      ]

print('Welcome to Kaun Banega Crorepati')
total_winning=0
prizeMoney=[1000, 25000]
for i,q in enumerate(questionBank):
  print(f"\n The {i+1} question for money {prizeMoney[i]} is in front of you \n")
  print(q["Question"])
  for option in q["option"]:
    print(option)

  user_input=input("Choose any 1 option A , B, C, D: or Press Q for Quit ")
  user_input = user_input.upper()
  if(user_input=="Q"):
    print(f"Thank you for game and you won {total_winning}")
    break
  if(user_input == q["Ans"]):
    total_winning+=prizeMoney[i]
    print(f"\n kya baat aap jeet chuke hai {total_winning}")

  else:
    print("Uff answer galat hai, GAME OVER!!")
    total_winning=0
    break