# -*- coding: utf-8 -*-
"""Untitled21.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FqlS4xKAk2CAfCHxGlHWO51NQrBaxky1
"""

for i in range(1,5):
   print("--student",i)

   for j in range(1,i+1):
    print("subject",j)

for i in range(1,5):
    print("--subject",i)

    for j in range(1,5-i+1):
     print("subject",j)

for i in range(1,5):
    print("--subject",i)

    for j in range(1,5+1-i):
     print("subject",j)

for i in range(1,5):
    print("--subject",i)

    for j in range(1,5-i+1):
     print("subject",j,end=" ")

    print("tea break")

for i in range(1,5):


    for j in range(1,5):
     print(j,end=" ")

    print("  ")

for i in range(1,5):

    for j in range(1,5):
     print(i,end=" ")

    print(" ")

for i in range(1,5):

    for j in range(4,0,-1):
     print(j,end=" ")

    print(" ")

a = 1
for i in range(1,4):

    for j in range(1,4):
     print(a,end=" ")
     a+=1

    print(" ")

for i in range(1,5):

    for j in range(1,i+1):
     print(j,end=" ")

    print(" ")

for i in range(1, 4):
    k = 4

    for j in range(i):
        print(k, end="")
        k += 1
    print(" ")

k = 1
for i in range(1, 5):


    for j in range(i):
        print(k, end=" ")
        k += 1
    print(" ")

x = 4
for i in range(1,5):

    for j in range(1,i+1):
     print(x,end=" ")
    x-=1

    print(" ")

for i in range(1,5):

    for j in range(65,i+65):
     print(chr(j),end=" ")

    print(" ")

x = 122
for i in range(1,4):

    for j in range(122,i+122):
     print(chr(x),end=" ")
     x-=1



    print(" ")

#assignment

for i in range(1,6):

    for j in range(1,i+1):
     print("*",end=" ")

    print(" ")

for i in range(1,5):

    for j in range(1,i+1):
     print(j,end=" ")

    print(" ")

k = 1
for i in range(1, 5):


    for j in range(i):
        print(k, end=" ")
        k += 1
    print(" ")

k = 1
for i in range(5,0,-1):

    for j in range(i):
     print("*",end=" ")
     k-=1

    print(" ")

k = 65
for i in range(4,0,-1):

    for j in range(65,i+65):
     print(chr (j),end=" ")
     k+=1

    print(" ")

for i in range(1,5):

    for j in range(1,i+1):
     print(i,end=" ")


    print(" ")

k = 4
for i in range(4,0,-1):

    for j in range(i,0,-1):
     print(j,end=" ")


    print(" ")

for i in range(1,5):

    for j in range(65,i+65):
     print(chr(j),end=" ")

    print(" ")

k = 5
for i in range(5,0,-1):

    for j in range(1,i+1):
     print( j,end=" ")
     k+=1

    print(" ")

for i in range(1,5):
    x = 4

    for j in range(5,i,-1):
     print(x,end=" ")
     x-=1


    print(" ")

for i in range(1,7):
    x = 70

    for j in range(7,i,-1):
     print(chr(x),end=" ")
     x-=1


    print(" ")

x = 10
for i in range(1,4):
    for i in range(1,i+1):
        print((x),end=" ")
        x+=1

    print(" ")

for i in range(1,5):
    x = 68

    for j in range(1,i+1):
        print(chr(x),end=" ")
        x-=1

    print(" ")

for i in range(1,5):
    x = 10

    for j in range(1,i+1):
        print((x),end=" ")
        x+=1

    print(" ")

for i in range(1,5):
    x = 68

    for j in range(5,i,-1):
     print(chr(x),end=" ")
     x-=1


    print(" ")

x = 70
for i in range(1,5):

    for j in range(1,i+1):
        print(chr(x),end= " ")
        x+=2

    print(" ")

for i in range(1,6):
    for j in range(1,i+1):
        if (j%2==0):
            print("2",end=" ")
        else:
            print("1",end=" ")


    print(" ")